/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {JrPageResponseJrCategoryResponse} from '../../models/jr-page-response-jr-category-response';

export interface FindAll3$Params {
  page?: number;
  size?: number;
}

export function findAll3(http: HttpClient, rootUrl: string, params?: FindAll3$Params, context?: HttpContext): Observable<StrictHttpResponse<JrPageResponseJrCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, findAll3.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JrPageResponseJrCategoryResponse>;
    })
  );
}

findAll3.PATH = '/api/v1/categories';
