/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create1 } from '../fn/movement/create-1';
import { Create1$Params } from '../fn/movement/create-1';
import { delete1 } from '../fn/movement/delete-1';
import { Delete1$Params } from '../fn/movement/delete-1';
import { findAll1 } from '../fn/movement/find-all-1';
import { FindAll1$Params } from '../fn/movement/find-all-1';
import { findById1 } from '../fn/movement/find-by-id-1';
import { FindById1$Params } from '../fn/movement/find-by-id-1';
import { JrPageResponseJrStockMvmtResponse } from '../models/jr-page-response-jr-stock-mvmt-response';
import { JrStockMvmtResponse } from '../models/jr-stock-mvmt-response';
import { update1 } from '../fn/movement/update-1';
import { Update1$Params } from '../fn/movement/update-1';


/**
 * Movement API
 */
@Injectable({ providedIn: 'root' })
export class MovementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findById1()` */
  static readonly FindById1Path = '/api/v1/stock-movements/{mvmtId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findById1()` instead.
   *
   * This method doesn't expect any request body.
   */
  findById1$Response(params: FindById1$Params, context?: HttpContext): Observable<StrictHttpResponse<JrStockMvmtResponse>> {
    const obs = findById1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findById1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findById1(params: FindById1$Params, context?: HttpContext): Observable<JrStockMvmtResponse> {
    const resp = this.findById1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<JrStockMvmtResponse>): JrStockMvmtResponse => r.body)
    );
  }

  /** Path part for operation `update1()` */
  static readonly Update1Path = '/api/v1/stock-movements/{mvmtId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update1$Response(params: Update1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = update1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update1(params: Update1$Params, context?: HttpContext): Observable<void> {
    const resp = this.update1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `delete1()` */
  static readonly Delete1Path = '/api/v1/stock-movements/{mvmtId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete1()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete1$Response(params: Delete1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = delete1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete1(params: Delete1$Params, context?: HttpContext): Observable<void> {
    const resp = this.delete1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAll1()` */
  static readonly FindAll1Path = '/api/v1/stock-movements';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAll1()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAll1$Response(params?: FindAll1$Params, context?: HttpContext): Observable<StrictHttpResponse<JrPageResponseJrStockMvmtResponse>> {
    const obs = findAll1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAll1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAll1(params?: FindAll1$Params, context?: HttpContext): Observable<JrPageResponseJrStockMvmtResponse> {
    const resp = this.findAll1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<JrPageResponseJrStockMvmtResponse>): JrPageResponseJrStockMvmtResponse => r.body)
    );
  }

  /** Path part for operation `create1()` */
  static readonly Create1Path = '/api/v1/stock-movements';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create1$Response(params: Create1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = create1(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create1(params: Create1$Params, context?: HttpContext): Observable<void> {
    const resp = this.create1$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
