/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/user/create';
import { Create$Params } from '../fn/user/create';
import { delete$ } from '../fn/user/delete';
import { Delete$Params } from '../fn/user/delete';
import { disable } from '../fn/user/disable';
import { Disable$Params } from '../fn/user/disable';
import { enable } from '../fn/user/enable';
import { Enable$Params } from '../fn/user/enable';
import { findAll } from '../fn/user/find-all';
import { FindAll$Params } from '../fn/user/find-all';
import { findById } from '../fn/user/find-by-id';
import { FindById$Params } from '../fn/user/find-by-id';
import { JrPageResponseJrUserResponse } from '../models/jr-page-response-jr-user-response';
import { JrUserResponse } from '../models/jr-user-response';
import { update } from '../fn/user/update';
import { Update$Params } from '../fn/user/update';


/**
 * User API
 */
@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findById()` */
  static readonly FindByIdPath = '/api/v1/users/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findById$Response(params: FindById$Params, context?: HttpContext): Observable<StrictHttpResponse<JrUserResponse>> {
    const obs = findById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findById(params: FindById$Params, context?: HttpContext): Observable<JrUserResponse> {
    const resp = this.findById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<JrUserResponse>): JrUserResponse => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/api/v1/users/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = update(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/api/v1/users/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = delete$(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<void> {
    const resp = this.delete$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `enable()` */
  static readonly EnablePath = '/api/v1/users/{userId}/enable';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `enable()` instead.
   *
   * This method doesn't expect any request body.
   */
  enable$Response(params: Enable$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = enable(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `enable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  enable(params: Enable$Params, context?: HttpContext): Observable<void> {
    const resp = this.enable$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `disable()` */
  static readonly DisablePath = '/api/v1/users/{userId}/disable';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `disable()` instead.
   *
   * This method doesn't expect any request body.
   */
  disable$Response(params: Disable$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = disable(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `disable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  disable(params: Disable$Params, context?: HttpContext): Observable<void> {
    const resp = this.disable$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAll()` */
  static readonly FindAllPath = '/api/v1/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAll$Response(params?: FindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<JrPageResponseJrUserResponse>> {
    const obs = findAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAll(params?: FindAll$Params, context?: HttpContext): Observable<JrPageResponseJrUserResponse> {
    const resp = this.findAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<JrPageResponseJrUserResponse>): JrPageResponseJrUserResponse => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/api/v1/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = create(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<void> {
    const resp = this.create$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
