/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JrStockMvmtResponse } from '../models/jr-stock-mvmt-response';
export interface JrPageResponseJrStockMvmtResponse {
  content?: Array<JrStockMvmtResponse>;
  first?: boolean;
  hasNext?: boolean;
  hasPrevious?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
