/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JrProductRequest {
  alertThreshold?: number;
  categoryId: string;
  description?: string;
  name: string;
  price: number;
  reference: string;
}
