/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {JrTenantResponse} from '../models/jr-tenant-response';

export interface JrPageResponseJrTenantResponse {
  content?: Array<JrTenantResponse>;
  first?: boolean;
  hasNext?: boolean;
  hasPrevious?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
