/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JrUserResponse } from '../models/jr-user-response';
export interface JrPageResponseJrUserResponse {
  content?: Array<JrUserResponse>;
  first?: boolean;
  hasNext?: boolean;
  hasPrevious?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
