/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {JrProductResponse} from '../models/jr-product-response';

export interface JrPageResponseJrProductResponse {
  content?: Array<JrProductResponse>;
  first?: boolean;
  hasNext?: boolean;
  hasPrevious?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
