/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JrCategoryResponse } from '../models/jr-category-response';
export interface JrPageResponseJrCategoryResponse {
  content?: Array<JrCategoryResponse>;
  first?: boolean;
  hasNext?: boolean;
  hasPrevious?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
