/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JrStockMvmtRequest {
  comment?: string;
  dateMvmt?: string;
  productId: string;
  quantity?: number;
  typeMvmt: 'IN' | 'OUT';
}


