/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JrStockMvmtResponse {
  comment?: string;
  dateMvmt?: string;
  quantity?: number;
  typeMvmt?: 'IN' | 'OUT';
}
