/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JrTenantResponse {
  adminEmail?: string;
  adminFirstName?: string;
  adminLastName?: string;
  adminPassword?: string;
  adminUsername?: string;
  companyCode?: string;
  companyEmail?: string;
  companyName?: string;
  createdAt?: string;
  status?: 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'INACTIVE';
  tenantId?: string;
}
