/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JrUserResponse {
  companyName?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  password?: string;
  role?: 'ROLE_PLATFORM_ADMIN' | 'ROLE_COMPANY_ADMIN' | 'ROLE_ADMINISTRATOR' | 'ROLE_SALES_OPERATOR' | 'ROLE_USER';
  username?: string;
}
