/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JrPageResponseJrStockMvmtResponse } from '../../models/jr-page-response-jr-stock-mvmt-response';

export interface FindAllByProductId$Params {
  productId: string;
  page?: number;
  size?: number;
}

export function findAllByProductId(http: HttpClient, rootUrl: string, params: FindAllByProductId$Params, context?: HttpContext): Observable<StrictHttpResponse<JrPageResponseJrStockMvmtResponse>> {
  const rb = new RequestBuilder(rootUrl, findAllByProductId.PATH, 'get');
  if (params) {
    rb.path('productId', params.productId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JrPageResponseJrStockMvmtResponse>;
    })
  );
}

findAllByProductId.PATH = '/api/v1/stock-movements/product/{productId}';
