/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { JrCategoryRequest } from './models/jr-category-request';
export type { JrCategoryResponse } from './models/jr-category-response';
export type { JrLoginRequest } from './models/jr-login-request';
export type { JrLoginResponse } from './models/jr-login-response';
export type { JrPageResponseJrCategoryResponse } from './models/jr-page-response-jr-category-response';
export type { JrPageResponseJrProductResponse } from './models/jr-page-response-jr-product-response';
export type { JrPageResponseJrStockMvmtResponse } from './models/jr-page-response-jr-stock-mvmt-response';
export type { JrPageResponseJrTenantResponse } from './models/jr-page-response-jr-tenant-response';
export type { JrPageResponseJrUserResponse } from './models/jr-page-response-jr-user-response';
export type { JrProductRequest } from './models/jr-product-request';
export type { JrProductResponse } from './models/jr-product-response';
export type { JrRegisterTenantRequest } from './models/jr-register-tenant-request';
export type { JrStockMvmtRequest } from './models/jr-stock-mvmt-request';
export type { JrStockMvmtResponse } from './models/jr-stock-mvmt-response';
export type { JrTenantResponse } from './models/jr-tenant-response';
export type { JrUserRequest } from './models/jr-user-request';
export type { JrUserResponse } from './models/jr-user-response';
